"""Edit network_activity model: add created_at, creator_id, updated_at

Revision ID: 6526bb10876c
Revises: 6e77ec7e563d
Create Date: 2026-09-16 16:27:36.008214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6526bb10876c'
down_revision: Union[str, Sequence[str], None] = '6e77ec7e563d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_activities', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('network_activities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('network_activities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'network_activities', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network_activities', type_='foreignkey')
    op.drop_column('network_activities', 'updated_at')
    op.drop_column('network_activities', 'created_at')
    op.drop_column('network_activities', 'creator_id')
    # ### end Alembic commands ###
