"""Init like, network_activity, user tables

Revision ID: 6e77ec7e563d
Revises: 
Create Date: 2026-09-16 14:22:03.639120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e77ec7e563d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_title', sa.String(length=100), nullable=False),
    sa.Column('activity_description', sa.String(length=500), nullable=False),
    sa.Column('average_traffic_mbps', sa.Integer(), nullable=False),
    sa.Column('max_latency_ms', sa.Integer(), nullable=False),
    sa.Column('preview_image_url', sa.String(length=255), nullable=False),
    sa.Column('preview_video_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'DELETED', 'DRAFT', name='activitystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_activities_id'), 'network_activities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['network_activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_network_activities_id'), table_name='network_activities')
    op.drop_table('network_activities')
    # ### end Alembic commands ###
